import argparse
from pathlib import Path


def register_commands(sub: argparse._SubParsersAction) -> None:
    init_cmd = sub.add_parser("init", help="Initialize run from a dataset")
    init_cmd.add_argument("--dataset", type=Path, required=True)
    init_cmd.add_argument("--target", type=str, required=True)
    init_cmd.add_argument("--objective", type=str, choices=["min", "max"], required=True)
    init_cmd.add_argument("--run-id", type=str, default=None)
    init_cmd.add_argument("--seed", type=int, default=7)
    init_cmd.add_argument("--engine", type=str, choices=["hebo", "bo_lcb", "random"], default="hebo")
    init_cmd.add_argument("--init-random", type=int, default=10)
    init_cmd.add_argument("--batch-size", type=int, default=1)
    init_cmd.add_argument("--max-categories", type=int, default=64)
    init_cmd.add_argument("--intent-json", type=str, default=None)
    init_cmd.add_argument("--verbose", action="store_true")

    suggest_cmd = sub.add_parser("suggest", help="Suggest next experimental candidates")
    suggest_cmd.add_argument("--run-id", type=str, required=True)
    suggest_cmd.add_argument("--batch-size", type=int, default=None)
    suggest_cmd.add_argument("--verbose", action="store_true")

    observe_cmd = sub.add_parser("observe", help="Record observation(s)")
    observe_cmd.add_argument("--run-id", type=str, required=True)
    observe_cmd.add_argument("--data", type=str, required=True)
    observe_cmd.add_argument("--verbose", action="store_true")

    status_cmd = sub.add_parser("status", help="Show run status")
    status_cmd.add_argument("--run-id", type=str, required=True)

    report_cmd = sub.add_parser("report", help="Generate report and plot")
    report_cmd.add_argument("--run-id", type=str, required=True)
    report_cmd.add_argument("--verbose", action="store_true")

    init_mol_cmd = sub.add_parser("init-molecular", help="Initialize a molecular optimization run from a scaffold spec")
    init_mol_cmd.add_argument("--scaffold-spec", type=Path, required=True)
    init_mol_cmd.add_argument("--target", type=str, required=True)
    init_mol_cmd.add_argument("--objective", type=str, choices=["min", "max"], required=True)
    init_mol_cmd.add_argument("--dataset", type=Path, default=None)
    init_mol_cmd.add_argument("--run-id", type=str, default=None)
    init_mol_cmd.add_argument("--seed", type=int, default=7)
    init_mol_cmd.add_argument("--engine", type=str, choices=["hebo", "bo_lcb", "random"], default="hebo")
    init_mol_cmd.add_argument("--init-random", type=int, default=10)
    init_mol_cmd.add_argument("--batch-size", type=int, default=1)
    init_mol_cmd.add_argument("--intent-json", type=str, default=None)
    init_mol_cmd.add_argument("--energy-backend", type=str, default=None, choices=["none", "xtb", "dft", "ml", "auto"])
    init_mol_cmd.add_argument("--verbose", action="store_true")

    feas_cmd = sub.add_parser("check-feasibility", help="Check synthesis feasibility of a molecule")
    feas_cmd.add_argument("--smiles", type=str, default=None)
    feas_cmd.add_argument("--run-id", type=str, default=None)
    feas_cmd.add_argument("--substituents", type=str, default=None)
    feas_cmd.add_argument("--sa-threshold", type=float, default=6.0)
    feas_cmd.add_argument("--strain-threshold", type=float, default=33.0)

    desc_cmd = sub.add_parser("compute-descriptors", help="Compute molecular descriptors for a SMILES")
    desc_cmd.add_argument("--smiles", type=str, required=True)
    desc_cmd.add_argument("--config", type=str, default=None)
    desc_cmd.add_argument("--energy-backend", type=str, default="none", choices=["none", "xtb", "dft", "ml", "auto"])

    draft_cmd = sub.add_parser("draft-scaffold-spec", help="Generate a draft scaffold spec from a SMILES with R-groups")
    draft_cmd.add_argument("--smiles", type=str, required=True)
    draft_cmd.add_argument("--positions", type=str, default=None)
    draft_cmd.add_argument("--output", type=Path, default=None)

    energy_cmd = sub.add_parser("compute-energy", help="Compute energy features for a single molecule")
    energy_cmd.add_argument("--smiles", type=str, required=True)
    energy_cmd.add_argument("--backend", type=str, default="xtb", choices=["xtb", "dft", "ml", "auto"])
    energy_cmd.add_argument("--solvent", type=str, default=None)

    precompute_cmd = sub.add_parser("precompute-energies", help="Precompute energy features for all scaffold+substituent combinations")
    precompute_cmd.add_argument("--run-id", type=str, required=True)
    precompute_cmd.add_argument("--backend", type=str, default="xtb", choices=["xtb", "dft", "ml", "auto"])
    precompute_cmd.add_argument("--solvent", type=str, default=None)
    precompute_cmd.add_argument("--verbose", action="store_true")

    se_cmd = sub.add_parser("scaffold-edit", help="Initialize CReM scaffold editing + HEBO optimisation run")
    se_cmd.add_argument("--dataset", type=Path, required=True)
    se_cmd.add_argument("--target", type=str, required=True)
    se_cmd.add_argument("--objective", type=str, choices=["min", "max"], required=True)
    se_cmd.add_argument("--smiles-column", type=str, default=None)
    se_cmd.add_argument("--seed-smiles", type=str, default=None)
    se_cmd.add_argument("--top-k-seeds", type=int, default=10)
    se_cmd.add_argument("--crem-db", type=Path, default=None)
    se_cmd.add_argument("--fixed-smarts", type=str, default=None)
    se_cmd.add_argument("--mutable-smarts", type=str, default=None)
    se_cmd.add_argument("--max-size", type=int, default=3)
    se_cmd.add_argument("--radius", type=int, default=3)
    se_cmd.add_argument("--max-replacements", type=int, default=100)
    se_cmd.add_argument("--operations", type=str, default=None)
    se_cmd.add_argument("--sa-threshold", type=float, default=6.0)
    se_cmd.add_argument("--run-id", type=str, default=None)
    se_cmd.add_argument("--seed", type=int, default=42)
    se_cmd.add_argument("--engine", type=str, default="hebo", choices=["hebo", "bo_lcb", "random"])
    se_cmd.add_argument("--fingerprint-bits", type=int, default=128)
    se_cmd.add_argument("--verbose", action="store_true")

    ae_cmd = sub.add_parser("augment-energy", help="Augment scaffold-edit candidates with xTB/DFT energy features")
    ae_cmd.add_argument("--run-id", type=str, required=True)
    ae_cmd.add_argument("--backend", type=str, default="xtb", choices=["xtb", "dft", "ml", "auto"])
    ae_cmd.add_argument("--verbose", action="store_true")

    top_cmd = sub.add_parser("top-candidates", help="Show top-K candidates from a completed optimisation run")
    top_cmd.add_argument("--run-id", type=str, required=True)
    top_cmd.add_argument("--top-k", type=int, default=10)
    top_cmd.add_argument("--verbose", action="store_true")

    val_cmd = sub.add_parser("validate", help="Validate top-K candidates with feasibility or xTB assessment")
    val_cmd.add_argument("--run-id", type=str, required=True)
    val_cmd.add_argument("--method", type=str, required=True, choices=["feasibility_only", "xtb_plus_feasibility"])
    val_cmd.add_argument("--top-k", type=int, default=10)
    val_cmd.add_argument("--verbose", action="store_true")

    screen_cmd = sub.add_parser("screen", help="One-command molecular virtual screening: CSV in, report out")
    screen_cmd.add_argument("--dataset", type=Path, required=True)
    screen_cmd.add_argument("--target", type=str, required=True)
    screen_cmd.add_argument("--objective", type=str, choices=["min", "max"], required=True)
    screen_cmd.add_argument("--smiles-column", type=str, default=None)
    screen_cmd.add_argument("--iterations", type=int, default=20)
    screen_cmd.add_argument("--seed", type=int, default=42)
    screen_cmd.add_argument("--engine", type=str, default="hebo", choices=["hebo", "bo_lcb", "random"])
    screen_cmd.add_argument("--batch-size", type=int, default=1)
    screen_cmd.add_argument("--fingerprint-bits", type=int, default=128)
    screen_cmd.add_argument("--energy-backend", type=str, default="none", choices=["none", "xtb", "auto"])
    screen_cmd.add_argument("--discovery", action="store_true")
    screen_cmd.add_argument("--verbose", action="store_true")

    smiles_discovery_cmd = sub.add_parser("smiles-discovery", help="Run EGFR-style discovery pipeline from one SMILES or a SMILES file")
    smiles_discovery_cmd.add_argument("--smiles", type=str, default=None)
    smiles_discovery_cmd.add_argument("--smiles-file", type=Path, default=None)
    smiles_discovery_cmd.add_argument("--dataset", type=Path, default=Path("data/egfr_quinazoline.csv"))
    smiles_discovery_cmd.add_argument("--target", type=str, default="pIC50")
    smiles_discovery_cmd.add_argument("--objective", type=str, choices=["min", "max"], default="max")
    smiles_discovery_cmd.add_argument("--iterations", type=int, default=20)
    smiles_discovery_cmd.add_argument("--batch-size", type=int, default=1)
    smiles_discovery_cmd.add_argument("--seed", type=int, default=42)
    smiles_discovery_cmd.add_argument("--engine", type=str, default="hebo", choices=["hebo", "bo_lcb", "random"])
    smiles_discovery_cmd.add_argument("--fingerprint-bits", type=int, default=256)
    smiles_discovery_cmd.add_argument("--energy-backend", type=str, default="none", choices=["none", "xtb", "auto"])
    smiles_discovery_cmd.add_argument("--top-k", type=int, default=10)
    smiles_discovery_cmd.add_argument("--verbose", action="store_true")

    egfr_global_cmd = sub.add_parser("egfr-ic50-global", help="Run the global EGFR IC50 experiment pipeline")
    egfr_global_cmd.add_argument("--dataset", type=Path, default=Path("data/egfr_ic50.csv"))
    egfr_global_cmd.add_argument("--target-column", default="ic50_nM", choices=["ic50_nM", "pIC50"])
    egfr_global_cmd.add_argument("--max-pic50", type=float, default=12.0)
    egfr_global_cmd.add_argument("--fix-tiny-ic50-as-molar", action="store_true")
    egfr_global_cmd.add_argument("--split-mode", default="auto", choices=["auto", "from-seed-csv"])
    egfr_global_cmd.add_argument("--seed-smiles-csv", type=Path, default=None)
    egfr_global_cmd.add_argument("--seed-smiles-column", default="smiles")
    egfr_global_cmd.add_argument("--seed-count", type=int, default=50)
    egfr_global_cmd.add_argument("--seed-top-fraction", type=float, default=0.1)
    egfr_global_cmd.add_argument("--seed-quality-mode", default="decent", choices=["top", "decent", "mixed"])
    egfr_global_cmd.add_argument("--seed-decent-low-q", type=float, default=0.60)
    egfr_global_cmd.add_argument("--seed-decent-high-q", type=float, default=0.90)
    egfr_global_cmd.add_argument("--no-seed-filter", action="store_true")
    egfr_global_cmd.add_argument("--iterations", type=int, default=30)
    egfr_global_cmd.add_argument("--rounds", type=int, default=15)
    egfr_global_cmd.add_argument("--batch-size", type=int, default=1)
    egfr_global_cmd.add_argument("--experiments-per-round", type=int, default=4)
    egfr_global_cmd.add_argument("--fp-bits", type=int, default=256)
    egfr_global_cmd.add_argument("--energy-backend", type=str, default="none", choices=["none", "xtb", "auto", "ml", "dft"])
    egfr_global_cmd.add_argument("--seed", type=int, default=42)
    egfr_global_cmd.add_argument("--ucb-beta", type=float, default=1.0)
    egfr_global_cmd.add_argument("--hebo-exploit-slots", type=int, default=1)
    egfr_global_cmd.add_argument("--hebo-explore-slots", type=int, default=0)
    egfr_global_cmd.add_argument("--hebo-explore-beta", type=float, default=2.0)
    egfr_global_cmd.add_argument("--all-hebo-exploit", action="store_true")
    egfr_global_cmd.add_argument("--adaptive-novelty", action=argparse.BooleanOptionalAction, default=True)
    egfr_global_cmd.add_argument("--novelty-grace-rounds", type=int, default=10)
    egfr_global_cmd.add_argument("--stall-rounds-threshold", type=int, default=3)
    egfr_global_cmd.add_argument("--verbose", action="store_true")
